import { LevelType } from "../types/types"

export const levels: Array<LevelType> = [
    {
        id: 0,
        title: 'Select all pots',
        plants: 2,
        flowers: 0,
        colorFlowers: ['red', 'red'],
        markup: ['<pot/>', '<pot/>'],
        animation: ['.pot-1', '.pot-2'],
        help: ['Type Selector',
            'Select elements by their type',
            'A',
            'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <span class="tag">div</span>, <span class="tag">p</span> and <span class="tag">ul</span> are all different element types.'],
        examples: [
            '<strong>div</strong> selects all <span class="tag">&lt;div&gt;</span> elements.',
            '<strong>p</strong> selects all <span class="tag">&lt;p&gt;</span> elements.',
        ],
        answer: 'pot',
    },
    {
        id: 1,
        title: 'Select the flower',
        plants: 3,
        flowers: 1,
        colorFlowers: ['red', 'red', 'red'],
        markup: ['<pot/>', '<pot/>', ['<flower id="flower"/>', '<pot/>']],
        animation: ['.flower-1'],
        help: ['ID Selector',
            'Select elements with an ID',
            '#id',
            'Selects the element with a specific <strong>id</strong>. You can also combine the ID selector with the type selector.'],
        examples: [
            '<strong>#cool</strong> selects any element with <strong>id="cool"</strong>',
            '<strong>ul#long</strong> selects <span class="tag">&lt;ul id="long"&gt;</span>'
        ],
        answer: '#flower',
    },
    {
        id: 2,
        title: 'Select all flowers',
        plants: 3,
        flowers: 2,
        colorFlowers: ['red', 'red', 'red'],
        markup: ['<pot/>', ['<flower/>', '<pot/>'], ['<flower/>', '<pot/>']],
        animation: ['.flower-1', '.flower-2'],
        help: ['Type Selector',
            'Select elements by their type',
            'A',
            'Selects all elements of type <strong>A</strong>. Type refers to the type of tag, so <span class="tag">div</span>, <span class="tag">p</span> and <span class="tag">ul</span> are all different element types.'],
        examples: [
            '<strong>div</strong> selects all <span class="tag">&lt;div&gt;</span> elements.',
            '<strong>p</strong> selects all <span class="tag">&lt;p&gt;</span> elements.',
        ],
        answer: 'flower',
    },
    {
        id: 3,
        title: 'Select all',
        plants: 4,
        flowers: 4,
        colorFlowers: ['red', 'red', 'red', 'red'],
        markup: [['<flower/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower/>', '<pot/>']],
        animation: ['.flower-1', '.flower-2', '.flower-3', '.flower-4', '.pot-1', '.pot-2', '.pot-3', '.pot-4'],
        help: ['The Universal Selector',
            'You can select everything!',
            '*',
            'You can select all elements with the universal selector!'],
        examples: [
            '<strong>p *</strong> selects any element inside all <span class="tag">&lt;p&gt;</span> elements.'
        ],
        answer: '*',
    },
    {
        id: 4,
        title: 'Select the first plant',
        plants: 3,
        flowers: 3,
        colorFlowers: ['red', 'red', 'red'],
        markup: [['<flower/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower/>', '<pot/>']],
        animation: ['.pot-1', '.flower-1'],
        help: ['First Child Pseudo-selector',
            'Select a first child element inside of another element',
            ':first-child',
            'You can select the first child element. A child element is any element that is directly nested in another element. You can combine this pseudo-selector with other selectors.'],
        examples: [
            '<strong>:first-child</strong> selects all first child elements.',
            '<strong>p:first-child</strong> selects all first child <span class="tag">&lt;p&gt;</span> elements.',
            '<strong>div p:first-child</strong> selects all first child <span class="tag">&lt;p&gt;</span> elements that are in a <div class="tag">div</div>.'
        ],
        answer: 'plants:first-child',
    },
    {
        id: 5,
        title: 'Select pink flowers',
        plants: 3,
        flowers: 3,
        colorFlowers: ['pink', 'red', 'pink'],
        markup: [['<flower class="pink"/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower class="pink/>', '<pot/>']],
        animation: ['.flower-1', '.flower-3'],
        help: ['Class Selector',
            'Select elements by their class',
            '.classname',
            'The class selector selects all elements with that class attribute. Elements can only have one ID, but many classes.'],
        examples: [
            '<strong>.neato</strong> selects all elements with <strong>class="neato"</strong>'
        ],
        answer: '.pink',
    },
    {
        id: 6,
        title: 'Select all flowers',
        plants: 4,
        flowers: 2,
        colorFlowers: ['red', 'red', 'red', 'pink'],
        markup: ['<pot/>', '<pot/>', ['<flower', '<pot/>'], ['<flower class="pink/>', '<pot/>']],
        animation: ['.flower-1', '.flower-2'],
        help: ['Child Selector',
            'Select direct children of an element',
            'A > B',
            'You can select elements that are direct children of other elements. A child element is any element that is nested directly in another element.Elements that are nested deeper than that are called descendant elements.'],
        examples: [
            '<strong>A > B</strong> selects all <strong>B</strong> that are a direct children <strong>A</strong>'
        ],
        answer: 'plants > flower',
    },
    {
        id: 7,
        title: 'Select the last plant',
        plants: 4,
        flowers: 4,
        colorFlowers: ['pink', 'pink', 'pink', 'pink'],
        markup: [['<flower class="pink/>', '<pot/>'], ['<flower class="pink/>', '<pot/>'], ['<flower class="pink/>', '<pot/>'], ['<flower class="pink/>', '<pot/>']],
        animation: ['.flower-4', '.pot-4'],
        help: ['Last Child Pseudo-selector',
            'Select the last element inside of another element',
            ':last-child',
            'You can use this selector to select an element that is the last child element inside of another element.'],
        examples: [
            '<strong>span:last-child</strong> selects all last-child <span class="tag">span</span> elements.',
            '<strong>ul li:last-child</strong> selects the last <span class="tag">li</span> elements inside of any <span class="tag">ul</span>.'
        ],
        answer: 'plants:last-child',
    },
    {
        id: 8,
        title: 'Select the third plant',
        plants: 5,
        flowers: 5,
        colorFlowers: ['pink', 'red', 'pink', 'red', 'pink'],
        markup: [['<flower class="pink/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower class="pink/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower class="pink/>', '<pot/>']],
        animation: ['.flower-3', '.pot-3'],
        help: ['Nth Child Pseudo-selector',
            'Select an element by its order in another element',
            ':nth-child(A)',
            'Selects the <strong>nth</strong> (Ex: 1st, 3rd, 12th etc.) child element in another element.'],
        examples: [
            '<strong>:nth-child(8)</strong> selects every element that is the 8th child of another element.',
            '<strong>div p:nth-child(2)</strong> selects the second <strong>p</strong> in every <strong>div</strong>',
        ],
        answer: ':nth-child(3)',
    },
    {
        id: 9,
        title: 'Select all even plates',
        plants: 5,
        flowers: 5,
        colorFlowers: ['pink', 'red', 'pink', 'red', 'pink'],
        markup: [['<flower class="pink/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower class="pink/>', '<pot/>'], ['<flower/>', '<pot/>'], ['<flower class="pink/>', '<pot/>']],
        animation: ['.flower-2', '.pot-2', '.flower-4', '.pot-4'],
        help: ['Nth of Type Selector',
            'Select an element by of Type Selector',
            ':nth-of-type(A)',
            'Selects a specific element based on its type and order in another element - or even or odd instances of that element.'],
        examples: [
            '<strong>div:nth-of-type(2)</strong> selects the second instance of a div.',
            '<strong>.example:nth-of-type(odd)</strong> selects all odd instances of a the example class.',
        ],
        answer: 'plants:nth-of-type(even)',
    },
]
